name: 123

on:
    workflow_dispatch:
    schedule:
        - cron: "30 */8 * * *"
    watch:
        types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.2'

    - name: PyExecJS
      run: |
        pip install PyExecJS
        
    - name: requests
      run: |
        pip install requests
        
    - name: Run
      run: |
        python postcode.py
